- alias: run_set_desired_temperature
  trigger:
    platform: state
    entity_id: input_number.desired_temperature
  action:
    service: shell_command.set_desired_temperature
- alias: run_set_current_temperature
  trigger:
    platform: state
    entity_id: sensor.living_room_multisensor_6_temperature
  action:
    service: shell_command.set_current_temperature
- alias: run_report_motion_living_room
  trigger:
    platform: state
    entity_id: sensor.living_room_multisensor_6_burglar
  action:
    service: shell_command.report_motion
- alias: run_report_motion_living_room_basement
  trigger:
    platform: state
    entity_id: sensor.first_floor__multisensor_6_burglar
  action:
    service: shell_command.report_motion
