- alias: run_set_desired_temperature
  trigger:
    platform: state
    entity_id: input_number.desired_temperature
  action:
    service: shell_command.set_desired_temperature
- alias: run_set_desired_temperature
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_temperature_3 
  action:
    service: shell_command.set_current_temperature
